### ISSUE TITLE
There are no user rights in the Linux version

### ISSUE THREAD

**Issue by Vochatrak-az-ezm** [CapitaineJSparrow/emusak-ui#111]
When downloading mods for Yuzu, the mod files do not have rights. Because of this, the emulator crashes when trying to access the mod files.

```
pwd
/home/dna/.local/share/yuzu/load/0100E95004038000/SuperSampling x2/exefs
```

```
ls -l
итого 4
------x--- 1 dna dna 304 июл 20 20:18 2.1.0.pchtxt
```

**Comment by CapitaineJSparrow** [comment]
Hey @Vochatrak-az-ezm Can you tell me which chmod is correct ? Maybe a `chmod 600 file.pchtxt` is enough ?

**Comment by Vochatrak-az-ezm** [comment]
Yes, it is enough, but I would recommend 660 so that there would be access for the user group.

**Comment by CapitaineJSparrow** [comment]
Hello @Vochatrak-az-ezm ,

This should has been fixed with 1.0.92, can you confirm the issue is fixed ? I applied a 660 chmod

**Comment by Vochatrak-az-ezm** [comment]
It seems to be working.

**Comment by CapitaineJSparrow** [comment]
As always, thanks for reporting and testing @Vochatrak-az-ezm
