### ISSUE TITLE
Make EmuSAK localizable

### ISSUE THREAD

**Issue by FrogAddict** [CapitaineJSparrow/emusak-ui#134]
It would be nice to have EmuSAK localizable into different languages.

**Comment by Danik2343** [comment]
Yes, i want to Translate to Russian Language. (Native speaker.)

**Comment by CapitaineJSparrow** [comment]
With Emusak V2, there is a full ability to translate the application by copy pasting this file : https://github.com/CapitaineJSparrow/emusak-ui/blob/emusak-v2/src/renderer/i18n/en.json The language selector is not implemented howevether i'm using react i18n which is build for that.

**Comment by viny182** [comment]
Hello @CapitaineJSparrow! I've created the Brazillian Portuguese translation from the en.json file above and attached below here as a .txt file because I did not know how to send it in a different way here in GitHub. Feel free to add it to the project, with no credits required. Keep the fantastic work, sir!

[pt-BR.txt](https://github.com/CapitaineJSparrow/emusak-ui/files/8019664/pt-BR.txt)

**Comment by viny182** [comment]
by the way, in the line 16 from the en.json file isn't a typo mistaked here?

16:  "launchRyujinx":   [...] Please note if you never launched the game in **yuzu**

shouldn't be Ryujinx instead Yuzu here?

**Comment by CapitaineJSparrow** [comment]
Hello @viny182 Thanks for your work ! 

![image](https://user-images.githubusercontent.com/6690149/152896290-c744783d-f098-40bc-b012-88d36b416f7d.png)
![image](https://user-images.githubusercontent.com/6690149/152896336-3acfa9c3-23d0-41b0-a8a5-7e2fbf3033cd.png)

(second screen is still WIP) You are completely right I fixed the typo on translations. If you want you can DM me your github email on discord (`Capitaine J. Sparrow#0096`) so I can do a co-author commit.

**Comment by viny182** [comment]
EmuSak looks great in portuguese @CapitaineJSparrow ! Thanks for adding it! <3

I've noticed a small typo mistake in line 3 in the translation I've provided and pointed the fix in #161  

From now on, I'll keep an eye whenever the en.json file gets updated, so I can keep up with the BR translation. :D

BR

**Comment by CapitaineJSparrow** [comment]
Next time you can edit the BR file directly on github, it will create a pull request I have to approve and you'll have full credits.
https://github.com/CapitaineJSparrow/emusak-ui/blob/emusak-v2/src/renderer/i18n/br.json

![image](https://user-images.githubusercontent.com/6690149/152897552-207d5026-74c7-4192-a12e-add912b9f47b.png)

**Comment by CapitaineJSparrow** [comment]
@Danik2343 @viny182 Can you review translations files ? I almost finished V2 and close to release it to everyone but I added some translations. Here are related files :

BR : https://github.com/CapitaineJSparrow/emusak-ui/blob/emusak-v2/src/renderer/i18n/br.json
RU : https://github.com/CapitaineJSparrow/emusak-ui/blob/emusak-v2/src/renderer/i18n/ru.json

Thanks 🤟

**Comment by viny182** [comment]
> @Danik2343 @viny182 Can you review translations files ? I almost finished V2 and close to release it to everyone but I added some translations. Here are related files :
> 
> BR : https://github.com/CapitaineJSparrow/emusak-ui/blob/emusak-v2/src/renderer/i18n/br.json RU : https://github.com/CapitaineJSparrow/emusak-ui/blob/emusak-v2/src/renderer/i18n/ru.json
> 
> Thanks 🤟

Done, changes proposed direct on the BR.json file. Always a pleasure!

**Comment by CapitaineJSparrow** [comment]
Hey @viny182 Thanks for your work but unfortunately I can't find it anywhere :D I think you did on your fork https://github.com/viny182/emusak-ui/branches ("patch-1" branch) but you did not created the pull request from your fork to emusak (a fork is a copy of this repository which belongs to you). You should take a look to this : https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by CapitaineJSparrow** [comment]
Hello everyone, I know it has been a while but I released emusak V2 as beta (current emusak will not auto update since it's a "pre-release"). This version includes localization (PT, BR, IT, DE, RU)

Feedbacks appreciated, it's `EmuSAK-win32-x64-2.0.0.zip` release for portable version****

**Comment by CapitaineJSparrow** [comment]
Should have been fixed by emusak V2 https://github.com/CapitaineJSparrow/emusak-ui/releases
