### ISSUE TITLE
support for Ryujinx vulkan shaders

### ISSUE THREAD

**Issue by theSpool** [CapitaineJSparrow/emusak-ui#136]
Maybe not urgent since it's still not merged but maybe at least keep this open until it's done.

Ryujinx under Vulkan performance is pretty awesome so it would be nice to not miss out on vuilkan shader caches if possible

**Comment by theSpool** [comment]
Oops, I'm heavily misinformed then. Thank you for the fast response, feel free to close this.

**Comment by CapitaineJSparrow** [comment]
All contributions as feature request or bug report are all welcome, thanks for the interest to the project !
