### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by JaleSwiftpaw** [CapitaineJSparrow/emusak-ui#139]
**Describe the bug**
Downloaded the installer for Windows, in this case, **_emusak-1.0.108.Setup.exe_**. Then I double click it and/or right click it and run as administrator and nothing happens.

**To Reproduce**
- Download installer.
- Double click it or right click it and run as Administrator.

**Expected behavior**
Setup program to run, or show any window at the very least.

**Did you used fitgirl repack to install Ryujinx**
No.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro 64-bit
 - Version 21H1 (10.0.19043.1288)

https://user-images.githubusercontent.com/93559140/139760088-444b7aa5-cca4-44dd-b15d-c498af561ca5.mp4

**Comment by CapitaineJSparrow** [comment]
Hey there, 

You are the only one to report an installation issue. You should definitely look at your antivirus probably preventing you to setup program. What is your antivirus ?

**Comment by JaleSwiftpaw** [comment]
Antivirus is Windows Defender and yes, I've turned it off completely. As I've seen with some YouTube videos (tutorials), a blue screen (SmartScreen) should appear, but in my case it shows absolutely nothing.

**Comment by Eduzord** [comment]
Hi there! I've also stumbled with this very problem. I've done the same steps as the OP and I also can't run the program. I've even tryed to add a Firewall exception to the launcher but still can't run the exe.  I also use only Windows Defender

**Comment by Eduzord** [comment]
Ok, so, even though the setup didn't show up when I clicked it, the files were actually installed on my PC on my AppData/Local folder. I tried to run the emusak.exe inside the 0.108 release folder and still couldn't get the program to launch. I also noticed that on my Task Manager there's 4 emusak.exe showing up despinte no signs of the application running anywhere.

**Comment by CapitaineJSparrow** [comment]
Actually that's really weird. I think that's the updater / installer not working correctly on your end for some reason (I use https://github.com/Squirrel/Squirrel.Windows which is the thing included in discord for example and very popular). I really suspect a permission issue and updater borked for some reason. i'll probably be able to handle this issue with a portable mode for emusak

**Comment by leoalmeidasant** [comment]
Hi, I've been having an error with starting up application too, but in my case, the app open but never finish downloading files from emusak.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/17017833/151722125-cc28e21f-a109-4f84-afdd-57b6ec8ef58f.png">

I've tried to stop antivirus and restart computer multiple times but still stucks in this step.

**Comment by CapitaineJSparrow** [comment]
Hello @leoalmeidasant nothing related to installer here I just messed up some DNS config, type `ipconfig /flushdns` to refresh your DNS and it will work again

**Comment by Festivize** [comment]
I had this same issue but after running the setup as administrator, it worked. I know OP's already running it as administrator but for those who haven't tried it yet and they're having the same issue, there you go.

**Comment by CapitaineJSparrow** [comment]
Hello everyone, I know it has been a while but I released emusak V2 as beta (current emusak will not auto update since it's a "pre-release"). This version includes a portable version without installer : https://github.com/CapitaineJSparrow/emusak-ui/releases It is supposed to fix this issue. I don't know why for few people squirrel is not working, it's a workaroung but it works

**Comment by CapitaineJSparrow** [comment]
Should have been fixed by emusak V2 : https://github.com/CapitaineJSparrow/emusak-ui/releases
