### ISSUE TITLE
Portable Release

### ISSUE THREAD

**Issue by CailanVR** [CapitaineJSparrow/emusak-ui#141]
I feel like a portable release would be useful to have, if possible.

**Comment by BurAndBY** [comment]
+1

**Comment by CapitaineJSparrow** [comment]
Definitely planned with emusak V2 !

**Comment by RMED24** [comment]
Also resolved for linux installs with the support of AppImage

**Comment by CapitaineJSparrow** [comment]
Hello everyone, I know it has been a while but I released emusak V2 as beta (current emusak will not auto update since it's a "pre-release"). This version includes a portable version without installer : https://github.com/CapitaineJSparrow/emusak-ui/releases

Feedbacks appreciated, it's `EmuSAK-win32-x64-2.0.0.zip` release for portable version

**Comment by CapitaineJSparrow** [comment]
> Is it possible to make it completely portable without it storing data in AppData but instead store it in the program folder?

Sadly no, i took a look and the technologies I'm using ( electron) are based on chromium (aka google chrome ) to render the UI. This come with pros ( emisak is coded like any website ) and cons ( mostly bc browser are storing data in appdata ) and I did not found a way to override this behavior. I made the uninstaller clean everything but there is no uninstaller With portable version so I'll instead put a button to clear this data in the software before you relive the portable version.

**Comment by CapitaineJSparrow** [comment]
Also electron is used in slack discord visual studio or even blizzard launcher and they all suffer from same issues

**Comment by CapitaineJSparrow** [comment]
That said I did not gave up and I'll try to prevent files to be written in appData

**Comment by CapitaineJSparrow** [comment]
Hello @Netrex I succeed to prevent appData folder to be used. Instead I'll use a folder "electron_cache" alongside Emusak.exe on portable mode here is a screenshot : 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/6690149/154070726-8bd72a83-94d4-4a5c-b90a-8e8777a4f03c.png">

There is [still an issue](https://github.com/electron/electron/issues/24536) where appData/emuSAK folder is still created but it's empty so it's not a big deal. This feature will be available in next emusak beta. Also note there is no auto updates on portable version (but there is a banner to tell you a new update is available)

**Comment by Netrex** [comment]
> Hello @Netrex I succeed to prevent appData folder to be used. Instead I'll use a folder "electron_cache" alongside Emusak.exe on portable mode here is a screenshot :
> 
> <img alt="image" width="1279" src="https://user-images.githubusercontent.com/6690149/154070726-8bd72a83-94d4-4a5c-b90a-8e8777a4f03c.png">
> 
> There is [still an issue](https://github.com/electron/electron/issues/24536) where appData/emuSAK folder is still created but it's empty so it's not a big deal. This feature will be available in next emusak beta. Also note there is no auto updates on portable version (but there is a banner to tell you a new update is available)

Perfect! Good work. Now the program is thumb drive friendly

**Comment by CapitaineJSparrow** [comment]
I dropped a second beta, you can take a look here : https://github.com/CapitaineJSparrow/emusak-ui/releases/tag/v2.0.1

**Comment by CapitaineJSparrow** [comment]
Should have been fixed by emusak V2 https://github.com/CapitaineJSparrow/emusak-ui/releases
