### ISSUE TITLE
This is not a portable yuzu path

### ISSUE THREAD

**Issue by munkor** [CapitaineJSparrow/emusak-ui#143]
I apologise immediately for maybe wasting your time, as i am sure this is a me issue but for the life of me, i cant work it out. As directed, when asked for my yuzu location, and am told 'This is not a portable yuzu path'

I'm assuming its something to do with my yuzu install not being portable, but i have no idea. The exe is in the folder i selected, i have tried 2 different paths / drives and still get no joy.

interestingly, the games i do have installed on my yuzu install, do appear in the program, but the exe issue still remains.

again, I'm sorry wasting your time on something that will likely be my stupidity, but any help would be appreciated

M

**Comment by CapitaineJSparrow** [comment]
If you are not using yuzu portable mode you don't need to use this button and your games should be automatically be listed in the software

**Comment by CapitaineJSparrow** [comment]
Does my last reply answer your question ? So I can close this issue
