### ISSUE TITLE
Ryujinx folder is not the .exe folder

### ISSUE THREAD

**Issue by GF-Huang** [CapitaineJSparrow/emusak-ui#144]
![image](https://user-images.githubusercontent.com/4510984/146289286-284ca03b-76f4-4b42-b692-082b731bb95f.png)

![image](https://user-images.githubusercontent.com/4510984/146289334-3b70f1e0-c67b-4533-ab17-027c2e34b407.png)

![image](https://user-images.githubusercontent.com/4510984/146289400-02837d8d-5522-4edb-b44d-e5ba6ff94b3e.png)

**Comment by edisionnano** [comment]
Could you elaborate please?

**Comment by CapitaineJSparrow** [comment]
Pick the installation folder, emusak will detect the data folder itself

**Comment by GF-Huang** [comment]
Thanks for the tip.
