### ISSUE TITLE
Is this caused by shader cache?

### ISSUE THREAD

**Issue by GF-Huang** [CapitaineJSparrow/emusak-ui#145]
**Describe the bug**
Strange white edges.

**Expected behavior**
No white edges.

**Did you used fitgirl repack to install Ryujinx**
No

**Screenshots**
![image](https://user-images.githubusercontent.com/4510984/146300842-a35056c0-5055-419a-955f-48ef4467410d.png)

**Desktop (please complete the following information):**
- OS: Win10
- Version 1.0.7125

**Additional context**

**Comment by CapitaineJSparrow** [comment]
You need the "outline removal" mod available in emusak. Please do not create issue for emulation issue, this software cannot improve or degrade rendering.

**Comment by CapitaineJSparrow** [comment]
By the way because it seems you are not aware, Emusak is not linked to Ryujinx or Yuzu projects in any way, it's an independant project

**Comment by GF-Huang** [comment]
> You need the "outline removal" mod available in emusak. Please do not create issue for emulation issue, this software cannot improve or degrade rendering.

Sorry, I'm new here, but where to find the "outline removal" mod?
