### ISSUE TITLE
I want add Russian Translation.

### ISSUE THREAD

**Issue by Danik2343** [CapitaineJSparrow/emusak-ui#155]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I wanted to translate the interface into Russian. 

**Describe alternatives you've considered**
No.

**Additional context**
You can implement a program localization system for further translation into other languages.

**Comment by CapitaineJSparrow** [comment]
Hello, I'll close it since it's a duplicate of #134 i'll add more details in this issue right now 👍
