### ISSUE TITLE
libva error: /usr/lib/dri/i965_drv_video.so init failed

### ISSUE THREAD

**Issue by Gurren-Joestar** [CapitaineJSparrow/emusak-ui#157]
**Describe the bug**
There is a warning related with libva when running in terminal `emusak` (from AUR) or `./emusak` (from AppImage) on a prime computer (I'm not sure if this cause the slow start). A quick search makes me think its an external issue related with libva itself.

**To re Reproduce**
1. Type in terminal emusak (version 1.0.108)
2. See the error output, the game will start but it is a bit slow

**Expected behavior**
To not see the error output.

**Did you used fitgirl repack to install Ryujinx**
[No]

**Screenshots**
![image](https://user-images.githubusercontent.com/71229258/151725782-ef6f284d-5c2f-4866-ac02-a2ae154b4692.png)

**Desktop (please complete the following information):**
- OS: [Manjaro]
- Version [1.0.108]

**Additional context**
Also running emusak with prime-run results in:
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

Some links related with libva:
https://github.com/intel/libva/issues/375
https://github.com/intel/libva/issues/278

I'm not sure if this is the only package on having this issue , I just type in terminal to see what was causing an slow start on emusak

**Comment by CapitaineJSparrow** [comment]
As far as I know, it's a driver issue you have to resolve on your end ? Actually Emusak is based on a chromium engine to render UI (as HTML / CSS / JS) and this issue means it cannot get hardware acceleration. You can probably get rid of this error by using `emusak --disable-gpu --disable-software-rasterizer` to prevent GPU process to spawn

**Comment by Gurren-Joestar** [comment]
Using `emusak --disable-gpu --disable-software-rasterizer` makes the job done, I no longer see the error
