### ISSUE TITLE
switching to portablr deleted all save data

### ISSUE THREAD

**Issue by L8Black** [CapitaineJSparrow/emusak-ui#160]
**Describe the bug**
ive opened emusak and apply the portable mode, now all my save data is gone 

**To Reproduce**
1. Go to emusak
2. Click on portable

3.data deleted

**Expected behavior**
my shiny buizel id rip 

**Did you used fitgirl repack to install Ryujinx**
[no]

**Desktop (please complete the following information):**
- OS: windows
- Version 11

**Additional context**
please guide with help

**Comment by CapitaineJSparrow** [comment]
Hello, 

![image](https://user-images.githubusercontent.com/6690149/152576453-9c2cf4b5-cf67-4422-9a80-1faff383ac6f.png)
This is the popup showed when you clicked the "make portable" button and you didn't read. Actually you need to transfer saves from %appData%/Ryujinx to your portable folder or you can also revert this changed my removing the "portable" folder alongside Ryujinx.exe
