### ISSUE TITLE
[Suggestion] Removing games I dont have anymore

### ISSUE THREAD

**Issue by turkeynaruto** [CapitaineJSparrow/emusak-ui#189]
First of all EmuSAK v2 looks really nice :)

But I have a huge list of games now which I dont really have anymore because I finished them.
So the feature Request would be to fully delete those games from Ryujinx including Shadercache/PPTC.

**Comment by CapitaineJSparrow** [comment]
Hello,

Thanks for feedback and suggestion. If I do such a feature il will be by game so if you want to clean 200 games might be easier to just clean %appData%/Ryu or yuzu on your end

**Comment by CapitaineJSparrow** [comment]
Closing in favor of #219 Which is more detailed so there is no double issues for same thing
