### ISSUE TITLE
v2.0.1 beta - Portable - Doesn't load any contents

### ISSUE THREAD

**Issue by RavenMacDaddy** [CapitaineJSparrow/emusak-ui#202]
**Describe the bug**
Running the portable release of 2.0.1 beta, even though the status page says the service is up, it's just stuck at loading for both Yuzu and Ryujinx.

The stable release, meanwhile, loads the contents instantly.

I also tried making a clean install by deleting the contents of the folder for the app first; completely empty, extract this version again, and start it again - no difference.

**To Reproduce**
1. Run the portable release of 2.0.1 beta
2. Try the Yuzu and Ryujinx tab
3. Notice how neither of them loads - it's just stuck at the circle animation in the middle

**Expected behavior**
It should simply load the contents of both emulators, just like the stable version, as well as according to https://emusak.betteruptime.com/

**Did you used fitgirl repack to install Ryujinx**
No

**Screenshots**
![image](https://user-images.githubusercontent.com/67732686/154312146-a37c6747-de4b-44e7-81a7-72391497dc84.png)

**Desktop (please complete the following information):**
- OS: Windows 11 - 22000.493
- Version 2.0.1 beta

**Comment by CapitaineJSparrow** [comment]
Thanks @RavenMacDaddy For testing and report. I can confirm in rare cases it does not work in beta2 but can you test if beta1 is working ? https://github.com/CapitaineJSparrow/emusak-ui/releases/tag/v2.0.0 I think mainline and beta1 are working

**Comment by RavenMacDaddy** [comment]
It did work in the first beta, yes.

**Comment by RavenMacDaddy** [comment]
I encounter the same issue with beta 3; v2.0.2.

**Comment by RavenMacDaddy** [comment]
No worries. 

The changes in beta 4 seem to have fixed the issue.
