### ISSUE TITLE
Mod Download Path not Case Sensitive for Linux

### ISSUE THREAD

**Issue by KenJyn76** [CapitaineJSparrow/emusak-ui#205]
**Describe the bug**
In Linux, file paths are case sensitive. Emusak uses lower case letters for the path when downloading mods, instead of upper case ones.

**To Reproduce**
Download any mod with emusak, and check the folder that it downloads the mod to.

**Expected behavior**
Mods should be added to the existing path for whatever title you downloaded the mod to.

**Did you used fitgirl repack to install Ryujinx**
No

**Desktop (please complete the following information):**
- OS: Linux
- Version 1.0.109

**Comment by CapitaineJSparrow** [comment]
Hello @KenJyn76 Thanks for reporting. Can you give an example of **incorrect** and **correct** path ? I my experience it was lowercase on Ryujinx and uppercase on yuzu can you confirm and tell me which emulator are you using ? 🙏

**Comment by CapitaineJSparrow** [comment]
Should have been fixed by emusak V2 https://github.com/CapitaineJSparrow/emusak-ui/releases
