### ISSUE TITLE
[Bug] v2: Selected profile isn't persisted initially

### ISSUE THREAD

**Issue by RavenMacDaddy** [CapitaineJSparrow/emusak-ui#208]
**Describe the bug**
I noticed that after creating my portable profiles, both the Yuzu and Ryujinx tabs go back to the global profiles.

You've to actively select your created profiles again for the app to actually persist your selection.

**To Reproduce**
1. Create a profile.
2. Switch tabs back and forth.
3. Notice how the global profile is selected instead.
4. After making a selection in this instance, it will actually persist your selection.

**Expected behavior**
Since the user has actively created a separate profile - which is the active one after creation - I expect this created profile to be persisted immediately.

**Did you used fitgirl repack to install Ryujinx**
No

**Screenshots**
N/A

**Desktop (please complete the following information):**
- OS: Windows 11
- Version 2.0.4 RC1

**Additional context**
After you've finally made your selection persisted, it also applies to restarts of the app.

**Comment by CapitaineJSparrow** [comment]
Nice catch thanks, it will be addressed

**Comment by CapitaineJSparrow** [comment]
Should be fixed with V2.0.8 : https://github.com/CapitaineJSparrow/emusak-ui/releases
