### ISSUE TITLE
[Bug] v2: Created configurations are wiped after every update

### ISSUE THREAD

**Issue by RavenMacDaddy** [CapitaineJSparrow/emusak-ui#212]
**Describe the bug**
I noticed when updating my main installation to v2 that it was starting to use a portable setup even though it was a installer setup to begin with.

It was when going from 2.0.5 to 2.0.7 that it became apparent, cause my created profiles weren't there at all, then I checked the corresponding folder for the older version and noticed the electron folder for the portable data.

**To Reproduce**
1. Download an older v2 build like 2.0.5 - the installer version.
2. Create a profile for at least one of the emulators.
3. Go from the older v2 build to the newest one by letting the app download the newer build.
4. Start the newest build and notice how the profile isn't there - cause it's present in the folder of the older build.

**Expected behavior**
Since the installer version is being used, all of the data, including the config, should write and read to/from AppData.

**Did you used fitgirl repack to install Ryujinx**
No

**Desktop (please complete the following information):**
- OS: Windows 11
- Version 2.0.5 > 2.0.7

**Comment by CapitaineJSparrow** [comment]
Should be fixed with V2.0.8 : https://github.com/CapitaineJSparrow/emusak-ui/releases howerver update between 2.0.7 and 2.0.8 will wipe data again but further updates will not have this issue

**Comment by RavenMacDaddy** [comment]
Thing is, since the installer version has folders for each downloaded version, it doesn't wipe the data - it's present in the folder of the old version as described, but since it doesn't migrate the electron folder, you end up with nothing.

As long as the app uses appdata again and not the electron dir - which is for portable use - it should be fine.

I was surprised the electron dir was being created at all for this very reason. 

Very possible I'm being ignorant regarding the issue - this is what I've observed is happening.
