### ISSUE TITLE
[Suggestion] Add delete game feature

### ISSUE THREAD

**Issue by Vaskiemaia** [CapitaineJSparrow/emusak-ui#219]
**Is your feature request related to a problem? Please describe.**

Currently if you have a bunch of games added to Ryujinx EmuSAK will detect them and they will show on EmuSAK allowing to do a bunch of different things including downloading Shaders/Saves/Mods (as it knows where each are located due to using the same ID, just a different file structure.

The issue is that if at any given point you delete a bunch of games they will still appear (and clutter) EmuSAK. Depending on how many games you are testing out it can become a genuine problem.

**Describe the solution you'd like**

As i see it (no coding knowledge from my side) there are two possible solutions, one is UX related, the other one more Coding related.

UX - Allow the user to right click on the game that is showing on EmuSAK (but has been deleted by the user in the past) and it would give an option to hide it on EmuSAK. That would mean EmuSAK wouldn't get rid of any files, it would just not show that ID. You could even add a filter to show all games, even the ones that have been hidden.

Coding - Allow the user to right click on the game that is showing on EmuSAK (but has been deleted by the user in the past) and it would give an option to delete any and all files/folders related to that game from Ryujinx. That would be achieved by the same ID that EmuSAK already uses. Since EmuSAK knows the files/folders where anything related to an ID would be located (Save/Mod/Shader) it could delete them.

**Additional context**

Going forward i believe this will have to be dealt with at some point one way or another as not everyone has access to a lot of storage and will inevitably delete games.

**Comment by CapitaineJSparrow** [comment]
Hello @Vaskiemaia is it related to https://github.com/CapitaineJSparrow/emusak-ui/issues/189 ?

**Comment by Vaskiemaia** [comment]
Yes it is!

Unfortunately cleaning the Ryujinx/Yuzu folder is not a great solution. While it would solve it, it would also mean users losing their Shaders/Saves/Mods, or having to go through a lot of manual work to backup for the games they want to keep.

Most users are not aware of how the file structure on Ryujinx works, but since EmuSAK already accesses them, knows their location and knows the ID of the game, it would be possible to delete those remaining files.

I believe one of the two options above could work.

**Comment by CapitaineJSparrow** [comment]
Should be covered by emusak 2.1.1 just released
