### ISSUE TITLE
make portable action in v2.0

### ISSUE THREAD

**Issue by CuddleBear92** [CapitaineJSparrow/emusak-ui#231]
The older version of the client had a feature to make an emulator install portable and it was quite handy.
Will this see a return in 2.0 with due time?
If not, i think its a feature that should be in there.

**Comment by CapitaineJSparrow** [comment]
Hello, I got too many complains about this feature about data loss (because they are stored in appData instead portable folder) with paniqued users so I choose to remove it. To make it portable it's as simple as create a "portable" folder alongside Ryujinx.exe or "user" folder alongside "yuzu.exe"
