### ISSUE TITLE
[Suggestion] Add an option to make the GUI controller friendly for handled devices 

### ISSUE THREAD

**Issue by Shahil-Ayato** [CapitaineJSparrow/emusak-ui#236]
The long anticipated  Steamdeck has recently been released to the public and at the present time the UI for emusak isn’t great for controllers, if it can become something like steams big picture mode it can be very simple to navigate for couch play and steamdeck users.

**Comment by CapitaineJSparrow** [comment]
- [ ] Make window minimum width / height lower than actual requirements
- [ ] Add ability to use emusak using a controller
- [ ] Add ability to navigate in the app using buttons (ref #209)

I'm not sure of the following tasks to be listed on "discover" section on steam deck as we discussed in discord
- [ ] Add flatpak release
- [ ] Pass the process of flatpak validation

**Comment by CapitaineJSparrow** [comment]
Should be covered by emusak 2.1.4 https://github.com/CapitaineJSparrow/emusak-ui/releases
