### ISSUE TITLE
Show filename/path somewhere...

### ISSUE THREAD

**Issue by BigheadSMZ** [CapitaineJSparrow/emusak-ui#248]
**Is your feature request related to a problem? Please describe.**
Currently we can see all the titles in our collection, but there is no way to know which title belongs to which file. For some reason, some games can show up in the list twice or just show up as the ID with no idea of what file it belongs to.

**Describe the solution you'd like**
When clicking on a game, show the filename and/or full path to the title somewhere on the window. The ability to navigate the game's folder would be a neat bonus I guess.

**Comment by CapitaineJSparrow** [comment]
![image](https://user-images.githubusercontent.com/6690149/164087473-b9684fb8-7cbf-4c7e-b8c3-1206fd907588.png)

Sorry for late reply (vacations) but it's here if you hover the "I" icon

**Comment by CapitaineJSparrow** [comment]
> The ability to navigate the game's folder would be a neat bonus I guess. 

You can already do this using the "Open shader cache" or mods directory

![image](https://user-images.githubusercontent.com/6690149/164087932-f380aeb7-7d23-4bec-9a05-00c696210d10.png)
