### ISSUE TITLE
Emusak very slow download speed.

### ISSUE THREAD

**Issue by CloudHaze** [CapitaineJSparrow/emusak-ui#255]
Hello I'm written from here Venezuela and I wanted to ask if there is a way to improve the Emusak client download speed? i have 10mbps connection and by downloading a simple firmware took me hours, seems like i'm using a dial up connection or worse

Is there a way to improve this situation? thanks

**Comment by CapitaineJSparrow** [comment]
Hello,

I'm sorry there is not so much I can do for you 🫤 Server is located in Europe, did you tried with a VPN already ? Might help a bit

**Comment by CloudHaze** [comment]
Hello Capitaine thanks for reply so fast, highly appreciate, I will try a VPN thanks for the recommendation. 
I'm very new using Yuzu and Emusak, can i ask something? when downloading games for yuzu, we need to download NSP format? or  XCI?

Thanks.

**Comment by CapitaineJSparrow** [comment]
You should come to discord to discuss such things, the link is at top right in EmuSAK app

**Comment by CloudHaze** [comment]
Ok thanks so much I will.
