### ISSUE TITLE
Black window On Fedora 36 Wayland Nvidia Driver

### ISSUE THREAD

**Issue by yodatak** [CapitaineJSparrow/emusak-ui#262]
**Describe the bug**
I got a black window on Fedora 36 when ruining it 

**To Reproduce**
Install the rpm EmuSAK-2.1.9-1.x86_64
On a Fedora 36 on Wayland with Nvidia driver

And you got this by runing in command line 
```
EmuSAK  
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**Expected behavior**
Just run 

**Did you used fitgirl repack to install Ryujinx**
no 

**Screenshots**
Add screenshots to help explain your problem. Even it seems to be irrelevant this can probably help

**Desktop (please complete the following information):**
- Fedora 36
- Wayland 
- Nvidia Driver
- EmuSAK-2.1.9-1.x86_64

**Comment by yodatak** [comment]
Its maybe a libva error because of electron that use the gpu by default it works by runing 
`EmuSAK --disable-gpu`

**Comment by CapitaineJSparrow** [comment]
As far as I know, it's a driver issue you have to resolve on your end ? Actually Emusak is based on a chromium engine to render UI (as HTML / CSS / JS) and this issue means it cannot get hardware acceleration. You can probably get rid of this error by using `emusak --disable-gpu --disable-software-rasterizer` to prevent GPU process to spawn
